name: First Workflow

on:
  push:

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a String
        run: echo "Hello World 333222"

      - name: Multiline Commands
        run: |
          node --version
          npm --version
